### PR TITLE
[Updated] Consider scroll amount into the mouse wheel scroll condition

### PR DESCRIPTION
**Pull request by arguiot**
This PR is a copy of #26, but with the requested changes. It's a fix that I really want to see on horizontal, so that's why I allow myself to do it instead of the original author.

### CODE REVIEW

**Comment by matthijsoberon** [comment]
Thanks for contributing, looks great 👍 !

**Comment by marcbelletre** [comment]
Could you please consider publishing a new release with these changes to npmjs? :)

**Comment by matthijsoberon** [comment]
@marcbelletre just published v1.0.5 :)

**Comment by marcbelletre** [comment]
@matthijsoberon Awesome thank you!

**Pull request merged**
